### ISSUE TITLE
"Join Game" popup displays shadow of "Create New Game" popup

### ISSUE THREAD

**Issue by reb0und** [reb0und/olympics#3]

**Comment by reb0und** [comment]
After clicking "Create New Game" and then "Join Game", the "Join Game" text unintentionally serves as an overlay for "Create New Game". Possibly both are being displayed or one is still shown. 
<img width="361" alt="image" src="https://github.com/reb0und/olympics/assets/67512765/55a859b6-692b-4714-ae23-fcf360168229">

**Comment by Skparab1** [comment]
fixed in branch web
